table internetsales
	lineageTag: c360dfe9-683c-4529-88d8-3e4edb3d57aa
	sourceLineageTag: [dbo].[internetsales]

	measure 'Total Revenue' =
			
			SUM(internetsales[SalesAmount])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 386e8950-533f-40c2-a321-1c720c4204df

		changedProperty = Name

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Orders' =
			
			DISTINCTCOUNT(
			internetsales[SalesOrderNumber]
			)
		formatString: 0
		lineageTag: 4c27f2a3-1841-469d-aeff-8e36a8466c67

		changedProperty = Name

	measure 'Products Sold Quantity' =
			
			SUM(
			internetsales[OrderQuantity]
			)
		formatString: 0
		lineageTag: da4a284e-b830-414b-b520-e0074a4d41ef

		changedProperty = Name

	measure 'Total Cost' =
			
			SUM(
			internetsales[TotalProductCost]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d95900bf-6114-40de-b6f4-c2acc255927c

		changedProperty = Name

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Gross Profit' =
			
			[Total Revenue]
			-
			[Total Cost]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: a29e5492-7d55-42b2-9d20-d3df0f212698

		changedProperty = Name

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Profit Margin' =
			
			DIVIDE(
			[Gross Profit],
			[Total Revenue]
			)
		lineageTag: bd263f39-7676-4516-a67c-ce7b0ddce1b0

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Freight' =
			
			SUM(
			internetsales[Freight]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ec224ddd-83be-48bf-af5f-ee8938477a75

		changedProperty = Name

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Tax' =
			
			SUM(
			internetsales[TaxAmt]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: dc4ecf36-1a5e-4365-a6c2-8b2de4a88cb6

		changedProperty = Name

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 08546d0d-9bcc-4d41-a7db-eb00f3cfcedf
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: f72948cd-e83e-4c1e-833a-02e7067afa84
		sourceLineageTag: OrderDateKey
		summarizeBy: none
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		lineageTag: 16d85332-a9a3-4d6b-9c6a-c2872767bf62
		sourceLineageTag: DueDateKey
		summarizeBy: count
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: 265722f7-832f-48ef-bc17-de561b23a340
		sourceLineageTag: ShipDateKey
		summarizeBy: count
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 18f519f2-7fda-4a96-bbe7-28571409b1f5
		sourceLineageTag: CustomerKey
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: 642904b1-b8d0-4d40-9467-3917515a88c3
		sourceLineageTag: PromotionKey
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: c0b6d5c6-63d7-45f7-bfae-cb64b6ffacf3
		sourceLineageTag: CurrencyKey
		summarizeBy: none
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 184cdb3b-c54d-43e5-918f-0479b1a55ff0
		sourceLineageTag: SalesTerritoryKey
		summarizeBy: none
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: d828f179-4c22-4964-a695-15044bd7fa29
		sourceLineageTag: SalesOrderNumber
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: 1d6b077c-ae2c-4392-bc2f-f79714a9b99e
		sourceLineageTag: SalesOrderLineNumber
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column RevisionNumber
		dataType: int64
		formatString: 0
		lineageTag: 368eb2db-7542-4e18-a01f-5dc897ef50ff
		sourceLineageTag: RevisionNumber
		summarizeBy: sum
		sourceColumn: RevisionNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: b0944bec-9d40-4503-864d-3299fdc83c0d
		sourceLineageTag: OrderQuantity
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 68d197ea-3942-408c-a58e-07c186b9bd48
		sourceLineageTag: UnitPrice
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ExtendedAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: eebc7a9f-4597-4f5e-91ba-ee26663dee99
		sourceLineageTag: ExtendedAmount
		summarizeBy: sum
		sourceColumn: ExtendedAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column UnitPriceDiscountPct
		dataType: double
		lineageTag: a5c4b86c-86bf-4d16-a027-8cf866af207f
		sourceLineageTag: UnitPriceDiscountPct
		summarizeBy: sum
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountAmount
		dataType: double
		lineageTag: 5159db24-d4fa-4e81-bf3a-d8aabfc7e55a
		sourceLineageTag: DiscountAmount
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8facfad4-81b7-406e-a6f7-a3f50426a1cd
		sourceLineageTag: ProductStandardCost
		summarizeBy: sum
		sourceColumn: ProductStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column TotalProductCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: be9c106f-84a0-49b8-bf78-fd4f647a6fd3
		sourceLineageTag: TotalProductCost
		summarizeBy: sum
		sourceColumn: TotalProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column SalesAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 4db7a9a4-d276-4fda-8b93-194206f3c356
		sourceLineageTag: SalesAmount
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column TaxAmt
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 5b03698e-c63f-4b10-b26a-58f574797e75
		sourceLineageTag: TaxAmt
		summarizeBy: sum
		sourceColumn: TaxAmt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Freight
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f24b6299-758a-4d0c-9555-6422ef2f8fa4
		sourceLineageTag: Freight
		summarizeBy: sum
		sourceColumn: Freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 00462b66-a6e3-473e-813f-06f8de0f692e
		sourceLineageTag: OrderDate
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

	column DueDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 7e5e1ace-e05f-42c7-b45d-3710a04dac01
		sourceLineageTag: DueDate
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: dateTime
		formatString: General Date
		lineageTag: d32bc3dd-c211-43fe-b324-d0370c2a5b0c
		sourceLineageTag: ShipDate
		summarizeBy: none
		sourceColumn: ShipDate

		annotation SummarizationSetBy = Automatic

	partition internetsales = entity
		mode: directLake
		source
			entityName: internetsales
			schemaName: dbo
			expressionSource: 'DirectLake - lh_Silver'

